### ISSUE TITLE
Problem with anvil -p

### ISSUE THREAD

**Issue by gnidde** [anviljs/anvil.js#13]
Hi, I'm a newbie with JavaScript and is eager to try Anvil out. I get a problem with running the anvil -p command. I'm running Windows 7.
I get the error below. Is it an issue or am I doing something bad? I even tried to run my console as administrator but that didn't help.

Best regards

Anders

C:\Projects\web\mama>anvil -p
Checking for config...
Loading config...

fs.js:434
  return binding.symlink(pathModule._makeLong(destination),
                 ^
Error: EPERM, operation not permitted 'C:\Projects\web\mama\pavlov'
    at Object.symlinkSync (fs.js:434:18)
    at C:\Users\anlo\AppData\Roaming\npm\node_modules\anvil.js\lib\anvil.js:694:8
    at C:\Users\anlo\AppData\Roaming\npm\node_modules\anvil.js\lib\anvil.js:306:11
    at C:\Users\anlo\AppData\Roaming\npm\node_modules\anvil.js\lib\anvil.js:361:12
    at C:\Users\anlo\AppData\Roaming\npm\node_modules\anvil.js\lib\anvil.js:192:14
    at [object Object].<anonymous> (fs.js:115:5)
    at [object Object].emit (events.js:64:17)
    at afterRead (fs.js:1117:12)
    at Object.wrapper [as oncomplete](fs.js:254:17)

C:\Projects\web\mama>

**Comment by gnidde** [comment]
I actually got it to work right after posting this issue. When I created an empty file named pavlov in the root it worked to run anvil -p.

**Comment by arobson** [comment]
@gnidde, sorry about the trouble. The pavlov support as it exists in 0.6.7 is going away. Anvil will copy the following files into the project's 'ext' folder:
pavlov.js
qunit.js
quint.cs
jquery.js
anvilHook.js

If you're building an HTML page to run your pavlov tests, including these files from your project's ext folder will give you the same behavior as before.

The reason the pavlov feature was discontinued in the new version is because there isn't a great way for Anvil to currently understand what order the script tags should get emitted into the page it was generating.

If there's anything I can do to help you transition your project to the new version, please let me know and I'll be happy to help. Closing this issue for now since you can continue using Anvil v0.6.7 (npm install -g anvil.js@v0.6.7) and it appears to be working now.

Thanks,
Alex

**Comment by gnidde** [comment]
Thanks for the answer Alex. Great job with this little project. It's nice to use.
