### ISSUE TITLE
Anvil fails on scaffolding a new site into an existing directory

### ISSUE THREAD

**Issue by mikehostetler** [anviljs/anvil.js#18]
Tried to ask anvil to scaffold a new site into an existing directory and it failed:

``` shell
$ anvil --site existing-directory/
Creating scaffolding for new site project

stream.js:105
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, open 'ext/anvilHook.js'
```

I realize that Anvil may have never been intended to do this, it didn't fail gracefully so I wanted to record it.

**Comment by mikehostetler** [comment]
Upon further investigation, it actually creates the scaffold directories, but fails to create the build.json file

**Comment by arobson** [comment]
Scaffolding only makes sense for new projects because Anvil will always create any missing directories needed for the project when you start it up.

The default build.json file doesn't get created on start because Anvil will actually use the defaults if no build file is found. To create one, you can use:

### library projects

anvil --libfile {filename}

### site projects

anvil --sitefile {filename}

You don't need to provide any extension, it will do that for you.

We can change the behavior -- what would make this more intuitive?

**Comment by mikehostetler** [comment]
The behavior is perfectly fine, I just discovered some friction in how you get there.  

I did some more investigating last night and I ran into more problems.  I need to isolate a consistent test case and then I'm going to take a stab at fixing it <watchout! /> :-)

**Comment by ifandelse** [comment]
I'm trying to run `anvil --lib some.directory` and am getting the same error:

```
Creating scaffolding for new lib project
Ensuring project directory structure

stream.js:105
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, no such file or directory 'ext/anvilHook.js'
```

after this error, if I run an ls on the dir, I see:
`ext lib spec    src tmp`

the ext directory (mentioned in the error) is empty.
