### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by rauhryan** [anviljs/anvil.js#7]
Hey man,

I've been working on my own project similar to yours, it started off as some shell scripts and text files.

Looks like you have a huge head start on me. 

What can I do to help?

**Comment by arobson** [comment]
Awesome! Things are in a bit of flux as a rewrite has been started (reboot branch) so that Anvil can facilitate site/app/lib development vs. just lib development.

It's getting close to something that (kinda) works again and at that point it would be easier to ask for help on certain features. In the meantime, if you happen to glance at reboot and see ways to improve the quality of the code (I have been in code like heck mode), please feel free to make suggestions or pull requests. I am in the process of adding decent BDD style test coverage through Mocha.

Are you on Trello? I've been using it to track some of the rewrite work. It might be a nice way to coordinate efforts going forward.

**Comment by rauhryan** [comment]
Im not on trello, but I did write a kanban board for github ;)

http://lostechies.com/ryanrauh/2012/01/13/huboard-github-issues-made-awesome/

I'm coworkers with Dru Sellers, he suggested that I check out your project
because
we have similar needs in our app.

-Ryan

On Tue, Mar 27, 2012 at 4:14 PM, Alex Robson <
reply@reply.github.com
