### ISSUE TITLE
Output includes ^M for wrap's prefix and suffix

### ISSUE THREAD

**Issue by mxriverlynn** [anviljs/anvil.js#8]
I'm running OSX and when I build a project that has a "wrap" defined in the build.json, I ended up with `^M` at the end of the line for the prefix and the suffix. For example:

`define(['jquery', 'underscore', 'backbone'], function($, _, Backbone){^M`

this doesn't seem to be affecting things adversely when I run the output script in Chrome, but I haven't tried other browsers... and it's a little concerning.

How are you generating the "new line" character for the prefix / suffix?

**Comment by arobson** [comment]
Well that's awful. I am really sorry about that. I haven't caught that simply because I haven't really used wrap in my projects much these days.

"How are you generating the "new line" character for the prefix / suffix?"

Would you accept "naïvely" as the answer? Things are in flux a bit as I'm working on a rewrite with actual tests and everything : ) I would be interested in hearing what kinds of features you wished Anvil had, things you don't like, etc.

Thanks for the feedback!

**Comment by mxriverlynn** [comment]
:) no problem...

I've got Anvil in place with Backbone.Marionette now and I'm loving it so far. 

There's one immediate thing I'd like to see:
- Include a `license` property in the build.json file. This would contain the license text that gets put at the top of each build out put file, including the uglified/minified/gzipped versions
- Alternate of `license-file` property to read from a file

And then I wanted to ask if there's support for any testing engines other than qUnit? I use Jasmine and right now I'm running my test suite from the Jasmine gem. It's not a big deal to have a separate build and test setup, in my opinion. I'm just curious if it would let me use Jasmine instead of qUnit.

**Comment by arobson** [comment]
### Re: the bug

I couldn't repro this one, but likely I'm just deficient : ) I did change the way the newline works but I'm not sure that it will fix the issue you were seeing. Would you mind doing at least a local anvil install from npm to see if it fixes the issue?

### Other things

As far as the license bit goes, there's a finalize step that will let you specify text as a string or file for the purpose of licensing. However... in the new version I'm tempted to drop finalize out and just have wrap work for the purpose of adding license boilerplate and encourage folks to use actual source files for boilerplate code since you can import source into those. Thoughts?

I'm working on adding support for the Mocha test runner and don't mind taking a look at jasmine but I'm unfamiliar with it. The testing story for new Anvil will change for the better since I'm hoping to push the CI capabilities a bit.

**Comment by mxriverlynn** [comment]
oh, nice... I didn't see that finalize attribute before. that will work perfectly.

I don't think wrap and finalize should be put together. I'm using wrap to add AMD/RequireJS support around Marionette, and I want that to be uglified with everything else (compressing the variable names, etc). But I want to have my license file prepended to the top of the output after uglification.

A few other thoughts: 

### version number

Right now I have my version number set in a line of code and in the header comments of the file. When I switch over to using the `finalize-file` bits, I'll have to keep the version number set correctly in two locations. It would be nice to have a `version` attribute in the build along with a `version-file` counterpart, and have those inserted in to my placeholders for the license file and the code.

### Docco

Also: +1 for Docco support. I do that steps manually right. Will be nice to have that in Anvil. :)

### Focus, Or Re-think it

Lastly - this is starting to get close to a generic build tool like make / rake / cake / jake. at some point, you'll want to decide where to draw the line in order to keep Anvil focused. Otherwise you might want to consider turning anvil's code into custom build tasks for cake or another existing build tool (similar to what I did with Albacore: rake tasks for .net apps)

**Comment by arobson** [comment]
### Version Number

@ifandelse and I were talking the other day and brainstorming about versions. I thought it would be swell if you could have placeholders for boilerplates and then by convention populate version from the git tag. That way you could tag your versions and have the code reflect it. Adding an override to the build file is also fine by me. This dovetails into...

### Moar Convention

This is a less well developed thought, but I've been toying with making Anvil capable of self-configuring. Currently Anvil will try to build any directory structure and just use the default config. Not terribly helpful. What if Anvil inspected the tree looking for files that followed certain conventions in order to determine where certain kinds of inputs came from? A folder with files matching _.spec._ is a safe bet for where to run the tests. A folder with .html, .md, .haml, .markdown files is where markup is stored, etc. The idea being, Anvil would look at what's there and try to start you out with a build.json that tried to capture the conventions in your project.

What's your reaction to something like just having wrap-header/wrap-footer, final-header/final-footer files that get picked up by default? I don't have to take the config stuff away, but it might be nice if we can reduce the number of steps to get to the end result. If others like the idea, I really don't think these kinds of steps will require much effort and I'm a big fan of things that just work (as much as possible).

### Focus and Rethink?

The goal of Anvil is something that just does what it should without requiring a lot of explicit instruction. In a perfect world, I could run Anvil in a lib or site repo and have it do its thing without any/much setup. There's usually a lot of intentional data in a project's structure, the trick is identifying, capturing and leveraging it : )

If there are specific folder structures for sites or libs that you love, I'd appreciate it if you'd share them. It'd help inform what kinds of conventions Anvil can support out of the box.

**Comment by ifandelse** [comment]
I agree with @derickbailey's point about having license included after minification/etc, so +1 to the thought of a wrap-header, wrap-footer and then final-header, final-footer.

Regarding the "moar convention" thoughts - I think if you keep to the approach you've been taking (the "favor sophisticated convention" but allow for flexible configured overrides), then I love it.  The thing that has made the current version of anvil that i'm using so powerful and helpful is how _little_ configuring I need to do, and the fact that the changes I need the most (separate build output, etc.) can be inferred from lib structure and relationships.

**Comment by mxriverlynn** [comment]
that all sounds good to me.

**Comment by arobson** [comment]
Hey @derickbailey,

The RC for new Anvil is in place in master and available on npm. Would you mind checking to see if you're still getting garbage in your files when using the wrap feature?

Thanks.

**Comment by mxriverlynn** [comment]
this is working correctly now.
